steps:
  # build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gdg-cloud-run/cloud-run-hello-web-app:$COMMIT_SHA', '.']
  # update latest docker image tag with $COMMIT_SHA
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/gdg-cloud-run/cloud-run-hello-web-app:$COMMIT_SHA', 'gcr.io/gdg-cloud-run/cloud-run-hello-web-app:latest']
  # push docker image to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gdg-cloud-run/cloud-run-hello-web-app:latest']
  # deploy app on cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run' , 'deploy', 'cloud-run-hello-web-app', '--platform', 'managed', '--region', 'us-east1', '--image', 'gcr.io/gdg-cloud-run/cloud-run-hello-web-app:latest', '--set-env-vars', 'HELLO_API_URL=https://cloud-run-hello-api-zdfryc74pa-ue.a.run.app', '--service-account', 'cloud-run-hello-web-app', '--allow-unauthenticated']
