steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gdg-cloud-run/cloud-run-hello-web-app:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gdg-cloud-run/cloud-run-hello-web-app:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run' , 'deploy', 'cloud-run-hello-web-app', '--platform', 'managed', '--region', 'australia-southeast1', '--image', 'gcr.io/gdg-cloud-run/cloud-run-hello-web-app:$COMMIT_SHA', '--set-env-vars', 'HELLO_API_URL=https://cloud-run-hello-api-zdfryc74pa-ts.a.run.app', '--service-account', 'cloud-run-hello-web-app', '--allow-unauthenticated']
